/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {


    public static void main(String[] args) {

        Restaurant restaurant=new Restaurant("Mac",5,200);
        Shop shop=new Shop("Mac",3,"contanin defent food",12);
        Department department=new Department("Mac",4);
        Review review=new Review(1,"sadas","wesam");
        Theater theater=new Theater("Mac",4);

//for the restaurant method
        System.out.println(restaurant.getPrice());
        //for review method
        review.updateStars(1);
        System.out.println(review.getNumber());
        System.out.println(review.getBody());
        System.out.println(review.getAuthor());
review.setMoviesName("spider man");
//for the theater method
        theater.addMovies("ali");
theater.addMovies("sasd");
theater.addMovies("kl;");
theater.removeMovie("ali");
// for the department method
        department.addReview(review);
        System.out.println(department.getArr());

    }
}